# Category 1 — Basic SELECT, Filtering & Sorting
### Total Questions: 7

---

1. Return the name of the employee whose name starts with 'A'
2. Return the name of the companies which have at least 2 users who speak English and German
3. Retrieve the top 3 users who spent the most on Zomato
4. Find the employees who have been hired in the last 3 months
5. Write a query to display the total salary of each employee after adding 10% increment
6. Write a query to fetch details of all employees excluding HR and Admin departments
7. Print all the duplicate emails

Step 1 — Master Setup Notebook
 called SQL_Database_Setup.

Install & Import

In [ ]:
import sqlite3
import pandas as pd
import os

# Create database file — this saves to Colab's filesystem
_cwd = os.getcwd()
_db = os.path.join(_cwd, "sql_practice.db")
if not os.path.isfile(_db):
    _db = os.path.join(os.path.dirname(_cwd), "sql_practice.db")
conn = sqlite3.connect(_db)
print("✅ Database created!")

✅ Database created!

Table 1 employee_salary

In [ ]:
conn.execute("DROP TABLE IF EXISTS employee_salary")
conn.execute("""
CREATE TABLE employee_salary(
    did INTEGER,
    name_of_employee TEXT,
    salary INTEGER
)
""")
conn.executemany("INSERT INTO employee_salary VALUES (?,?,?)",[
    (1, 'Alice',   50000),
    (1, 'Bob',     65000),
    (1, 'Carol',   60000),
    (1, 'Dan',     72000),
    (1, 'Eve',     58000),
    (1, 'Frank',   69000),
    (2, 'Grace',   70000),
    (2, 'Henry',   82000),
    (2, 'Isla',    77000),
    (2, 'Jack',    91000),
    (2, 'Karen',   68000),
    (2, 'Leo',     75000),
    (3, 'Mia',     55000),
    (3, 'Nathan',  62000),
    (3, 'Olivia',  48000),
    (3, 'Paul',    71000),
    (3, 'Quinn',   53000),
    (3, 'Rachel',  66000)
])
conn.commit()
print("✅ employee_salary updated — 18 rows")
pd.read_sql_query("SELECT * FROM employee_salary", conn)

✅ employee_salary updated — 18 rows

    did name_of_employee  salary
0     1            Alice   50000
1     1              Bob   65000
2     1            Carol   60000
3     1              Dan   72000
4     1              Eve   58000
5     1            Frank   69000
6     2            Grace   70000
7     2            Henry   82000
8     2             Isla   77000
9     2             Jack   91000
10    2            Karen   68000
11    2              Leo   75000
12    3              Mia   55000
13    3           Nathan   62000
14    3           Olivia   48000
15    3             Paul   71000
16    3            Quinn   53000
17    3           Rachel   66000

**Table 2 emp**

In [ ]:
conn.execute("DROP TABLE IF EXISTS emp")
conn.execute("""
CREATE TABLE emp(
    id INTEGER,
    salary INTEGER
)
""")
conn.executemany("INSERT INTO emp VALUES (?,?)",[
    (1,  10000),
    (2,  15000),
    (3,  20000),
    (4,  20000),
    (5,  30000),
    (6,  30000),
    (7,  45000),
    (8,  50000),
    (9,  50000),
    (10, 75000)
])
conn.commit()
print("✅ emp — 10 rows")
pd.read_sql_query("SELECT * FROM emp", conn)

✅ emp — 10 rows

   id  salary
0   1   10000
1   2   15000
2   3   20000
3   4   20000
4   5   30000
5   6   30000
6   7   45000
7   8   50000
8   9   50000
9  10   75000

**Table 3 employees**

In [ ]:
conn.execute("DROP TABLE IF EXISTS employees")
conn.execute("""
CREATE TABLE employees(
    id INTEGER,
    name TEXT,
    salary INTEGER,
    dep_id INTEGER,
    manager_id INTEGER,
    hire_date DATE,
    email TEXT
)
""")
conn.executemany("INSERT INTO employees VALUES (?,?,?,?,?,?,?)",[
    (1, 'John',    60000, 1, None, '2026-01-15', 'john@gmail.com'),
    (2, 'Alice',   80000, 1, 1,    '2026-02-01', 'alice@gmail.com'),
    (3, 'Bob',     75000, 2, 1,    '2026-01-20', 'john@gmail.com'),
    (4, 'David',   50000, 2, 3,    '2026-03-01', 'bob@gmail.com'),
    (5, 'John',    45000, 3, 3,    '2026-02-15', 'david@gmail.com'),
    (6, 'Emma',    90000, 1, 1,    '2025-06-10', 'emma@gmail.com'),
    (7, 'Frank',   55000, 2, 3,    '2025-08-20', 'frank@gmail.com'),
    (8, 'Grace',   72000, 3, 5,    '2026-01-05', 'grace@gmail.com'),
    (9, 'Henry',   48000, 3, 5,    '2025-11-11', 'alice@gmail.com'),
    (10,'Isla',    95000, 1, 1,    '2025-04-01', 'isla@gmail.com'),
    (11,'Jack',    61000, 2, 3,    '2026-02-20', 'jack@gmail.com'),
    (12,'Karen',   83000, 1, 1,    '2025-07-15', 'karen@gmail.com'),
    (13,'Leo',     57000, 2, 3,    '2025-09-01', 'leo@gmail.com'),
    (14,'Mia',     74000, 3, 5,    '2026-01-25', 'mia@gmail.com'),
    (15,'Nathan',  66000, 1, 1,    '2025-12-01', 'nathan@gmail.com'),
    (16,'Olivia',  52000, 2, 3,    '2026-03-05', 'frank@gmail.com'),
    (17,'Paul',    88000, 3, 5,    '2025-05-20', 'paul@gmail.com'),
    (18,'Quinn',   43000, 1, 1,    '2026-02-10', 'quinn@gmail.com'),
    (19,'Rachel',  79000, 2, 3,    '2025-10-15', 'rachel@gmail.com'),
    (20,'Steve',   67000, 3, 5,    '2026-01-30', 'bob@gmail.com')
])
conn.commit()
print("✅ employees — 20 rows")
pd.read_sql_query("SELECT * FROM employees", conn)

✅ employees — 20 rows

    id    name  salary  dep_id  manager_id   hire_date             email
0    1    John   60000       1         NaN  2026-01-15    john@gmail.com
1    2   Alice   80000       1         1.0  2026-02-01   alice@gmail.com
2    3     Bob   75000       2         1.0  2026-01-20    john@gmail.com
3    4   David   50000       2         3.0  2026-03-01     bob@gmail.com
4    5    John   45000       3         3.0  2026-02-15   david@gmail.com
5    6    Emma   90000       1         1.0  2025-06-10    emma@gmail.com
6    7   Frank   55000       2         3.0  2025-08-20   frank@gmail.com
7    8   Grace   72000       3         5.0  2026-01-05   grace@gmail.com
8    9   Henry   48000       3         5.0  2025-11-11   alice@gmail.com
9   10    Isla   95000       1         1.0  2025-04-01    isla@gmail.com
10  11    Jack   61000       2         3.0  2026-02-20    jack@gmail.com
11  12   Karen   83000       1         1.0  2025-07-15   karen@gmail.com
12  13     Leo   57000       2         3.0  2025-09-01     leo@gmail.com
13  14     Mia   74000       3         5.0  2026-01-25     mia@gmail.com
14  15  Nathan   66000       1         1.0  2025-12-01  nathan@gmail.com
15  16  Olivia   52000       2         3.0  2026-03-05   frank@gmail.com
16  17    Paul   88000       3         5.0  2025-05-20    paul@gmail.com
17  18   Quinn   43000       1         1.0  2026-02-10   quinn@gmail.com
18  19  Rachel   79000       2         3.0  2025-10-15  rachel@gmail.com
19  20   Steve   67000       3         5.0  2026-01-30     bob@gmail.com


**Table  4 department**

In [ ]:
conn.execute("DROP TABLE IF EXISTS department")
conn.execute("""
CREATE TABLE department(
    id INTEGER,
    name TEXT
)
""")
conn.executemany("INSERT INTO department VALUES (?,?)",[
    (1,'IT'),
    (2,'Finance'),
    (3,'HR')
])
conn.commit()
print("✅ department created!")
pd.read_sql_query("SELECT * FROM department", conn)

✅ department created!

   id     name
0   1       IT
1   2  Finance
2   3       HR

**Table 5 num**

In [ ]:
conn.execute("DROP TABLE IF EXISTS num")
conn.execute("""
CREATE TABLE num(
    id INTEGER,
    numbers INTEGER
)
""")
conn.executemany("INSERT INTO num VALUES (?,?)",[
    (1,1),
    (2,1),
    (3,1),
    (4,2),
    (5,3),
    (6,3),
    (7,3),
    (8,3)
])
conn.commit()
print("✅ num created!")
pd.read_sql_query("SELECT * FROM num", conn)

✅ num created!

   id  numbers
0   1        1
1   2        1
2   3        1
3   4        2
4   5        3
5   6        3
6   7        3
7   8        3

**Table 6 temperature**

In [ ]:
conn.execute("DROP TABLE IF EXISTS temperature")
conn.execute("""
CREATE TABLE temperature(
    days DATE,
    temp INTEGER
)
""")
conn.executemany("INSERT INTO temperature VALUES (?,?)",[
    ('2024-01-01',20),
    ('2024-01-02',22),
    ('2024-01-03',21),
    ('2024-01-04',25),
    ('2024-01-05',26)
])
conn.commit()
print("✅ temperature created!")
pd.read_sql_query("SELECT * FROM temperature", conn)

✅ temperature created!

         days  temp
0  2024-01-01    20
1  2024-01-02    22
2  2024-01-03    21
3  2024-01-04    25
4  2024-01-05    26

**Table 7 seat**

In [ ]:
conn.execute("DROP TABLE IF EXISTS seat")
conn.execute("""
CREATE TABLE seat(
    id INTEGER,
    student TEXT
)
""")
conn.executemany("INSERT INTO seat VALUES (?,?)",[
    (1,'A'),
    (2,'B'),
    (3,'C'),
    (4,'D'),
    (5,'E')
])
conn.commit()
print("✅ seat created!")
pd.read_sql_query("SELECT * FROM seat", conn)

✅ seat created!

   id student
0   1       A
1   2       B
2   3       C
3   4       D
4   5       E

**Table 8 orders**

In [ ]:
conn.execute("DROP TABLE IF EXISTS orders")
conn.execute("""
CREATE TABLE orders(
    order_id INTEGER,
    customer_id INTEGER,
    amount INTEGER
)
""")
conn.executemany("INSERT INTO orders VALUES (?,?,?)",[
    (1,  1, 200),
    (2,  1, 150),
    (3,  2, 300),
    (4,  2, 450),
    (5,  3, 100),
    (6,  4, 550),
    (7,  4, 200),
    (8,  5, 320),
    (9,  6, 410),
    (10, 6, 180),
    (11, 7, 290),
    (12, 1, 500)
])
conn.commit()
print("✅ orders — 12 rows")
pd.read_sql_query("SELECT * FROM orders", conn)

✅ orders — 12 rows

    order_id  customer_id  amount
0          1            1     200
1          2            1     150
2          3            2     300
3          4            2     450
4          5            3     100
5          6            4     550
6          7            4     200
7          8            5     320
8          9            6     410
9         10            6     180
10        11            7     290
11        12            1     500

**Table 9 customers**

In [ ]:
conn.execute("DROP TABLE IF EXISTS customers")
conn.execute("""
CREATE TABLE customers(
    customer_id INTEGER,
    name TEXT
)
""")
conn.executemany("INSERT INTO customers VALUES (?,?)",[
    (1,  'Alice'),
    (2,  'Bob'),
    (3,  'Charlie'),
    (4,  'David'),
    (5,  'Emma'),
    (6,  'Frank'),
    (7,  'Grace'),
    (8,  'Henry'),
    (9,  'Isla'),
    (10, 'Jack')
])
conn.commit()
print("✅ customers — 10 rows")
pd.read_sql_query("SELECT * FROM customers", conn)

✅ customers — 10 rows

   customer_id     name
0            1    Alice
1            2      Bob
2            3  Charlie
3            4    David
4            5     Emma
5            6    Frank
6            7    Grace
7            8    Henry
8            9     Isla
9           10     Jack

**TABLE 10 zomato_orders**

In [ ]:
conn.execute("DROP TABLE IF EXISTS zomato_orders")
conn.execute("""
CREATE TABLE zomato_orders(
    user_id INTEGER,
    order_id INTEGER,
    amount INTEGER,
    order_date DATE,
    delivery_partner_id INTEGER,
    delivery_rating INTEGER
)
""")
conn.executemany("INSERT INTO zomato_orders VALUES (?,?,?,?,?,?)",[
    (1,101,200,'2024-01-01',1,5),
    (1,102,300,'2024-01-03',2,4),
    (2,103,150,'2024-01-04',1,5),
    (3,104,400,'2024-01-05',3,3)
])
conn.commit()
print("✅ zomato_orders created!")
pd.read_sql_query("SELECT * FROM zomato_orders", conn)

✅ zomato_orders created!

   user_id  order_id  amount  order_date  delivery_partner_id  delivery_rating
0        1       101     200  2024-01-01                    1                5
1        1       102     300  2024-01-03                    2                4
2        2       103     150  2024-01-04                    1                5
3        3       104     400  2024-01-05                    3                3

**TABLE 11 users**

In [ ]:
conn.execute("DROP TABLE IF EXISTS users")
conn.execute("""
CREATE TABLE users(
    user_id INTEGER,
    company TEXT,
    language TEXT
)
""")
conn.executemany("INSERT INTO users VALUES (?,?,?)",[
    (1,  'Google', 'English'),
    (2,  'Google', 'German'),
    (3,  'Google', 'French'),
    (4,  'Google', 'Spanish'),
    (5,  'Meta',   'English'),
    (6,  'Meta',   'Spanish'),
    (7,  'Meta',   'French'),
    (8,  'Apple',  'English'),
    (9,  'Apple',  'German'),
    (10, 'Apple',  'French'),
    (11, 'Amazon', 'English'),
    (12, 'Amazon', 'German'),
    (13, 'Amazon', 'Hindi'),
    (14, 'Netflix','French'),
    (15, 'Netflix','Spanish')
])
conn.commit()
print("✅ users — 15 rows")
pd.read_sql_query("SELECT * FROM users", conn)

✅ users — 15 rows

    user_id  company language
0         1   Google  English
1         2   Google   German
2         3   Google   French
3         4   Google  Spanish
4         5     Meta  English
5         6     Meta  Spanish
6         7     Meta   French
7         8    Apple  English
8         9    Apple   German
9        10    Apple   French
10       11   Amazon  English
11       12   Amazon   German
12       13   Amazon    Hindi
13       14  Netflix   French
14       15  Netflix  Spanish

**TABLE 12 monthly_salary**

In [ ]:
conn.execute("DROP TABLE IF EXISTS monthly_salary")
conn.execute("""
CREATE TABLE monthly_salary(
    emp_id INTEGER,
    month TEXT,
    salary INTEGER
)
""")
conn.executemany("INSERT INTO monthly_salary VALUES (?,?,?)",[
    (1,'Jan',5000),
    (1,'Feb',5000),
    (1,'Mar',5000),
    (1,'Apr',5000),
    (1,'May',5000),
    (1,'Jun',5000),
    (1,'Jul',5000),
    (2,'Jan',7000),
    (2,'Feb',7000),
    (2,'Mar',7000),
    (2,'Apr',7000),
    (2,'May',7000),
    (2,'Jun',7000),
    (2,'Jul',7000)
])
conn.commit()
print("✅ monthly_salary created!")
pd.read_sql_query("SELECT * FROM monthly_salary", conn)

✅ monthly_salary created!

    emp_id month  salary
0        1   Jan    5000
1        1   Feb    5000
2        1   Mar    5000
3        1   Apr    5000
4        1   May    5000
5        1   Jun    5000
6        1   Jul    5000
7        2   Jan    7000
8        2   Feb    7000
9        2   Mar    7000
10       2   Apr    7000
11       2   May    7000
12       2   Jun    7000
13       2   Jul    7000

**TABLE 13 products**

In [ ]:
conn.execute("DROP TABLE IF EXISTS products")
conn.execute("""
CREATE TABLE products(
    transaction_id INTEGER,
    product_id INTEGER,
    transaction_date DATE,
    spend INTEGER
)
""")
conn.executemany("INSERT INTO products VALUES (?,?,?,?)",[
    (1,101,'2022-01-01',1000),
    (2,101,'2022-06-01',1500),
    (3,101,'2023-01-01',1800),
    (4,101,'2023-06-01',2000),
    (5,102,'2022-03-01',500),
    (6,102,'2023-03-01',800),
    (7,102,'2024-03-01',1200)
])
conn.commit()
print("✅ products created!")
pd.read_sql_query("SELECT * FROM products", conn)

✅ products created!

   transaction_id  product_id transaction_date  spend
0               1         101       2022-01-01   1000
1               2         101       2022-06-01   1500
2               3         101       2023-01-01   1800
3               4         101       2023-06-01   2000
4               5         102       2022-03-01    500
5               6         102       2023-03-01    800
6               7         102       2024-03-01   1200

TABLE 14 posts

In [ ]:
conn.execute("DROP TABLE IF EXISTS posts")
conn.execute("""
CREATE TABLE posts(
    user_id INTEGER,
    date DATE,
    post_count INTEGER
)
""")
conn.executemany("INSERT INTO posts VALUES (?,?,?)",[
    (1,'2024-01-01',3),
    (1,'2024-01-02',5),
    (1,'2024-01-03',2),
    (1,'2024-01-04',8),
    (2,'2024-01-01',1),
    (2,'2024-01-02',4),
    (2,'2024-01-03',6)
])
conn.commit()
print("✅ posts created!")
pd.read_sql_query("SELECT * FROM posts", conn)

✅ posts created!

   user_id        date  post_count
0        1  2024-01-01           3
1        1  2024-01-02           5
2        1  2024-01-03           2
3        1  2024-01-04           8
4        2  2024-01-01           1
5        2  2024-01-02           4
6        2  2024-01-03           6

TABLE 15 & 16 table_x and table_y

In [ ]:
conn.execute("DROP TABLE IF EXISTS table_x")
conn.execute("CREATE TABLE table_x (ids INTEGER)")
conn.executemany("INSERT INTO table_x VALUES (?)",
    [(1,),(1,),(1,),(1,)])
conn.commit()

conn.execute("DROP TABLE IF EXISTS table_y")
conn.execute("CREATE TABLE table_y (ids INTEGER)")
conn.executemany("INSERT INTO table_y VALUES (?)",
    [(1,),(1,),(1,),(1,),(1,),(1,),(1,),(1,)])
conn.commit()
print("✅ table_x — 4 rows | table_y — 8 rows")
print("table_x:"); display(pd.read_sql_query("SELECT * FROM table_x", conn))
print("table_y:"); display(pd.read_sql_query("SELECT * FROM table_y", conn))

✅ table_x — 4 rows | table_y — 8 rows
table_x:

   ids
0    1
1    1
2    1
3    1

table_y:

   ids
0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1

Table 17 & 18 a & b

In [ ]:
# 🛠️ Create table_a
conn.execute("DROP TABLE IF EXISTS table_a")
conn.execute("""
CREATE TABLE table_a(
    col INTEGER
)
""")
conn.executemany("INSERT INTO table_a VALUES (?)",
    [(1,),(1,),(1,),(2,),(2,),(3,),(4,),(5,)])
conn.commit()

# 🛠️ Create table_b
conn.execute("DROP TABLE IF EXISTS table_b")
conn.execute("""
CREATE TABLE table_b(
    col INTEGER
)
""")
conn.executemany("INSERT INTO table_b VALUES (?)",
    [(1,),(1,),(2,),(2,),(2,),(3,),(3,),(3,),(4,)])
conn.commit()

# 👀 Preview Tables
print("table_a:")
pd.read_sql_query("SELECT * FROM table_a", conn)

table_a:

   col
0    1
1    1
2    1
3    2
4    2
5    3
6    4
7    5

In [ ]:
# 👀 Preview Table B
print("table_b:")
pd.read_sql_query("SELECT * FROM table_b", conn)

table_b:

   col
0    1
1    1
2    2
3    2
4    2
5    3
6    3
7    3
8    4

Tables

In [ ]:
# ✅ Verify all tables
tables = pd.read_sql_query("""
SELECT name FROM sqlite_master
WHERE type='table' ORDER BY name
""", conn)
print(f"✅ Total tables: {len(tables)}")
display(tables)

✅ Total tables: 18

               name
0         customers
1        department
2               emp
3   employee_salary
4         employees
5    monthly_salary
6               num
7            orders
8             posts
9          products
10             seat
11          table_a
12          table_b
13          table_x
14          table_y
15      temperature
16            users
17    zomato_orders

Save & Download the Database

In [ ]:
# ✅ Close connection — this saves the file
conn.close()
print("✅ Database saved as sql_practice.db")

# ⬇️ Download the file to your computer
from google.colab import files
files.download("sql_practice.db")

✅ Database saved as sql_practice.db

Upload the database

In [ ]:
# ⬆️ Upload sql_practice.db from your computer
from google.colab import files
uploaded = files.upload()
print("✅ Database uploaded!")

Saving sql_practice (2).db to sql_practice (2).db
✅ Database uploaded!

Connect to it

In [ ]:
import sqlite3
import pandas as pd
import os

_cwd = os.getcwd()
_db = os.path.join(_cwd, "sql_practice.db")
if not os.path.isfile(_db):
    _db = os.path.join(os.path.dirname(_cwd), "sql_practice.db")
conn = sqlite3.connect(_db)

# Verify tables loaded
pd.read_sql_query("""
SELECT name FROM sqlite_master
WHERE type='table'
ORDER BY name
""", conn)

               name
0         customers
1        department
2               emp
3   employee_salary
4         employees
5    monthly_salary
6               num
7            orders
8             posts
9          products
10             seat
11          table_a
12          table_b
13          table_x
14          table_y
15      temperature
16            users
17    zomato_orders

# Category 1 — Basic SELECT, Filtering & Sorting

## 1. Employees Whose Name Starts With 'A'

**Difficulty:** 🟢 Easy

**Subtopic:** LIKE / Filtering

---

**Table: employee_salary**
```
+------------------+---------+
| Column Name      | Type    |
+------------------+---------+
| did              | int     |
| name_of_employee | varchar |
| salary           | int     |
+------------------+---------+
```

- `did` represents the department ID.
- `name_of_employee` represents the employee's name.
- `salary` represents the employee's salary.

Each department may contain multiple employees.

---

**Problem**

Write a SQL query to return the name of the employee whose name starts with the letter **'A'**.

Return the result in any order.

**Example 1**

**Input**

employee_salary table:
```
+-----+------------------+--------+
| did | name_of_employee | salary |
+-----+------------------+--------+
| 1   | Alice            | 50000  |
| 1   | Bob              | 65000  |
| 1   | Carol            | 60000  |
| 2   | David            | 70000  |
| 2   | Emma             | 72000  |
| 2   | Frank            | 68000  |
| 3   | Anna             | 55000  |
| 3   | George           | 52000  |
| 3   | Henry            | 51000  |
+-----+------------------+--------+
```

**Output**
```
+------------------+
| name_of_employee |
+------------------+
| Alice            |
| Anna             |
+------------------+
```

---

In [ ]:
# 👀 Preview the table
print("employee_salary table:")
pd.read_sql_query("SELECT * FROM employee_salary", conn)

employee_salary table:

    did name_of_employee  salary
0     1            Alice   50000
1     1              Bob   65000
2     1            Carol   60000
3     1              Dan   72000
4     1              Eve   58000
5     1            Frank   69000
6     2            Grace   70000
7     2            Henry   82000
8     2             Isla   77000
9     2             Jack   91000
10    2            Karen   68000
11    2              Leo   75000
12    3              Mia   55000
13    3           Nathan   62000
14    3           Olivia   48000
15    3             Paul   71000
16    3            Quinn   53000
17    3           Rachel   66000

SOLUTION

In [ ]:

query = """
SELECT name_of_employee
FROM employee_salary
WHERE name_of_employee LIKE 'A%'
"""

pd.read_sql_query(query, conn)

  name_of_employee
0            Alice

**Explanation**

- `WHERE` filters rows before any grouping or aggregation.
- `LIKE 'A%'` matches any name that **starts with the letter 'A'** — the `%` is a wildcard that means *"anything can follow"*.
- Only `Alice` and `Anna` satisfy this condition from the table.

# Q2. Employees Hired in the Last 3 Months

## 2. Employees Hired in the Last 3 Months

**Difficulty:** 🟢 Easy

**Subtopic:** DATE Filtering

---

**Table: employees**
```
+------------+---------+
| Column Name| Type    |
+------------+---------+
| id         | int     |
| name       | varchar |
| salary     | int     |
| dep_id     | int     |
| manager_id | int     |
| hire_date  | date    |
+------------+---------+
```

- `id` represents the employee ID.
- `name` represents the employee's name.
- `hire_date` represents the date the employee joined.

---

**Problem**

Write a SQL query to find all employees who were hired in the **last 3 months** from today.

Return all columns for matching employees.

**Example 1**

**Input**

employees table:
```
+----+-------+--------+--------+------------+------------+
| id | name  | salary | dep_id | manager_id | hire_date  |
+----+-------+--------+--------+------------+------------+
| 1  | John  | 60000  | 1      | NULL       | 2023-01-01 |
| 2  | Alice | 80000  | 1      | 1          | 2023-03-01 |
| 3  | Bob   | 75000  | 2      | 1          | 2023-05-01 |
| 4  | David | 50000  | 2      | 3          | 2024-01-01 |
+----+-------+--------+--------+------------+------------+
```

**Output** *(assuming today is 2024-03-01)*
```
+----+-------+--------+--------+------------+------------+
| id | name  | salary | dep_id | manager_id | hire_date  |
+----+-------+--------+--------+------------+------------+
| 4  | David | 50000  | 2      | 3          | 2024-01-01 |
+----+-------+--------+--------+------------+------------+
```

(View Table):

In [ ]:
# 👀 Preview the table
print("employees table:")
pd.read_sql_query("SELECT * FROM employees", conn)

employees table:

    id    name  salary  dep_id  manager_id   hire_date             email
0    1    John   60000       1         NaN  2026-01-15    john@gmail.com
1    2   Alice   80000       1         1.0  2026-02-01   alice@gmail.com
2    3     Bob   75000       2         1.0  2026-01-20    john@gmail.com
3    4   David   50000       2         3.0  2026-03-01     bob@gmail.com
4    5    John   45000       3         3.0  2026-02-15   david@gmail.com
5    6    Emma   90000       1         1.0  2025-06-10    emma@gmail.com
6    7   Frank   55000       2         3.0  2025-08-20   frank@gmail.com
7    8   Grace   72000       3         5.0  2026-01-05   grace@gmail.com
8    9   Henry   48000       3         5.0  2025-11-11   alice@gmail.com
9   10    Isla   95000       1         1.0  2025-04-01    isla@gmail.com
10  11    Jack   61000       2         3.0  2026-02-20    jack@gmail.com
11  12   Karen   83000       1         1.0  2025-07-15   karen@gmail.com
12  13     Leo   57000       2         3.0  2025-09-01     leo@gmail.com
13  14     Mia   74000       3         5.0  2026-01-25     mia@gmail.com
14  15  Nathan   66000       1         1.0  2025-12-01  nathan@gmail.com
15  16  Olivia   52000       2         3.0  2026-03-05   frank@gmail.com
16  17    Paul   88000       3         5.0  2025-05-20    paul@gmail.com
17  18   Quinn   43000       1         1.0  2026-02-10   quinn@gmail.com
18  19  Rachel   79000       2         3.0  2025-10-15  rachel@gmail.com
19  20   Steve   67000       3         5.0  2026-01-30     bob@gmail.com

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT *
FROM employees
WHERE hire_date >= DATE('now', '-3 months')
"""

pd.read_sql_query(query, conn)

    id    name  salary  dep_id  manager_id   hire_date            email
0    1    John   60000       1         NaN  2026-01-15   john@gmail.com
1    2   Alice   80000       1         1.0  2026-02-01  alice@gmail.com
2    3     Bob   75000       2         1.0  2026-01-20   john@gmail.com
3    4   David   50000       2         3.0  2026-03-01    bob@gmail.com
4    5    John   45000       3         3.0  2026-02-15  david@gmail.com
5    8   Grace   72000       3         5.0  2026-01-05  grace@gmail.com
6   11    Jack   61000       2         3.0  2026-02-20   jack@gmail.com
7   14     Mia   74000       3         5.0  2026-01-25    mia@gmail.com
8   16  Olivia   52000       2         3.0  2026-03-05  frank@gmail.com
9   18   Quinn   43000       1         1.0  2026-02-10  quinn@gmail.com
10  20   Steve   67000       3         5.0  2026-01-30    bob@gmail.com

> **Note:** Since our sample data uses older dates,

> we demonstrate the concept by replacing `DATE('now', '-3 months')`

> with a fixed reference date. In a real scenario `DATE('now')`

> would always refer to today's date automatically.

# Q3. Display Total Salary After 10% Increment

## 3. Display Total Salary After 10% Increment

**Difficulty:** 🟢 Easy

**Subtopic:** Arithmetic / Derived Columns

---

**Table: employee_salary**
```
+------------------+---------+
| Column Name      | Type    |
+------------------+---------+
| did              | int     |
| name_of_employee | varchar |
| salary           | int     |
+------------------+---------+
```

- `did` represents the department ID.
- `name_of_employee` represents the employee's name.
- `salary` represents the employee's salary.

---

**Problem**

Write a SQL query to display the **name** and **new salary** of each employee after adding a **10% increment** to their existing salary.

**Example 1**

**Input**

employee_salary table:
```
+-----+------------------+--------+
| did | name_of_employee | salary |
+-----+------------------+--------+
| 1   | Alice            | 50000  |
| 1   | Bob              | 65000  |
| 1   | Carol            | 60000  |
| 2   | David            | 70000  |
| 2   | Emma             | 72000  |
| 2   | Frank            | 68000  |
| 3   | Anna             | 55000  |
| 3   | George           | 52000  |
| 3   | Henry            | 51000  |
+-----+------------------+--------+
```

**Output**
```
+------------------+------------+
| name_of_employee | new_salary |
+------------------+------------+
| Alice            | 55000.0    |
| Bob              | 71500.0    |
| Carol            | 66000.0    |
| David            | 77000.0    |
| Emma             | 79200.0    |
| Frank            | 74800.0    |
| Anna             | 60500.0    |
| George           | 57200.0    |
| Henry            | 56100.0    |
+------------------+------------+
```

CODE (View Table):

In [ ]:
# 👀 Preview the table
print("employee_salary table:")
pd.read_sql_query("SELECT * FROM employee_salary", conn)

employee_salary table:

   did name_of_employee  salary
0    1            Alice   50000
1    1              Bob   65000
2    1            Carol   60000
3    2            David   70000
4    2             Emma   72000
5    2            Frank   68000
6    3             Anna   55000
7    3           George   52000
8    3            Henry   51000

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT name_of_employee,
       salary * 1.10 AS new_salary
FROM employee_salary
"""

pd.read_sql_query(query, conn)

  name_of_employee  new_salary
0            Alice     55000.0
1              Bob     71500.0
2            Carol     66000.0
3            David     77000.0
4             Emma     79200.0
5            Frank     74800.0
6             Anna     60500.0
7           George     57200.0
8            Henry     56100.0

**Explanation**

- `salary * 1.10` multiplies each employee's salary by 1.10 which adds a 10% increment.
- `AS new_salary` renames the calculated column to `new_salary` in the output.
- No `WHERE` or `GROUP BY` is needed — this applies to every row in the table.

# New Section

# 4. Fetch All Employees Excluding HR and Admin

**Difficulty:** 🟢 Easy

**Subtopic:** NOT IN / Filtering + JOIN

---

**Tables: employees + department**
```
employees
+------------+---------+
| Column Name| Type    |
+------------+---------+
| id         | int     |
| name       | varchar |
| salary     | int     |
| dep_id     | int     |
| manager_id | int     |
| hire_date  | date    |
+------------+---------+

department
+------------+---------+
| Column Name| Type    |
+------------+---------+
| id         | int     |
| name       | varchar |
+------------+---------+
```

- `dep_id` in employees links to `id` in department.
- `name` in department represents the department name.

---

**Problem**

Write a SQL query to fetch details of all employees **excluding** those who belong to **'HR'** and **'Admin'** departments.

**Example 1**

**Input**

employees table:
```
+----+-------+--------+--------+------------+------------+
| id | name  | salary | dep_id | manager_id | hire_date  |
+----+-------+--------+--------+------------+------------+
| 1  | John  | 60000  | 1      | NULL       | 2023-01-01 |
| 2  | Alice | 80000  | 1      | 1          | 2023-03-01 |
| 3  | Bob   | 75000  | 2      | 1          | 2023-05-01 |
| 4  | David | 50000  | 2      | 3          | 2024-01-01 |
+----+-------+--------+--------+------------+------------+
```

department table:
```
+----+---------+
| id | name    |
+----+---------+
| 1  | IT      |
| 2  | Finance |
| 3  | HR      |
+----+---------+
```

**Output**
```
+----+-------+--------+--------+
| id | name  | salary | dep_id |
+----+-------+--------+--------+
| 1  | John  | 60000  | 1      |
| 2  | Alice | 80000  | 1      |
| 3  | Bob   | 75000  | 2      |
+----+-------+--------+--------+
```

(View Tables):

In [ ]:
# 👀 Preview Table 1
print("employees table:")
pd.read_sql_query("SELECT * FROM employees", conn)

employees table:

    id    name  salary  dep_id  manager_id   hire_date             email
0    1    John   60000       1         NaN  2026-01-15    john@gmail.com
1    2   Alice   80000       1         1.0  2026-02-01   alice@gmail.com
2    3     Bob   75000       2         1.0  2026-01-20    john@gmail.com
3    4   David   50000       2         3.0  2026-03-01     bob@gmail.com
4    5    John   45000       3         3.0  2026-02-15   david@gmail.com
5    6    Emma   90000       1         1.0  2025-06-10    emma@gmail.com
6    7   Frank   55000       2         3.0  2025-08-20   frank@gmail.com
7    8   Grace   72000       3         5.0  2026-01-05   grace@gmail.com
8    9   Henry   48000       3         5.0  2025-11-11   alice@gmail.com
9   10    Isla   95000       1         1.0  2025-04-01    isla@gmail.com
10  11    Jack   61000       2         3.0  2026-02-20    jack@gmail.com
11  12   Karen   83000       1         1.0  2025-07-15   karen@gmail.com
12  13     Leo   57000       2         3.0  2025-09-01     leo@gmail.com
13  14     Mia   74000       3         5.0  2026-01-25     mia@gmail.com
14  15  Nathan   66000       1         1.0  2025-12-01  nathan@gmail.com
15  16  Olivia   52000       2         3.0  2026-03-05   frank@gmail.com
16  17    Paul   88000       3         5.0  2025-05-20    paul@gmail.com
17  18   Quinn   43000       1         1.0  2026-02-10   quinn@gmail.com
18  19  Rachel   79000       2         3.0  2025-10-15  rachel@gmail.com
19  20   Steve   67000       3         5.0  2026-01-30     bob@gmail.com

In [ ]:
# 👀 Preview Table 2
print("department table:")
pd.read_sql_query("SELECT * FROM department", conn)

department table:

   id     name
0   1       IT
1   2  Finance
2   3       HR

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT e.*
FROM employees e
JOIN department d ON e.dep_id = d.id
WHERE d.name NOT IN ('HR', 'Admin')
"""

pd.read_sql_query(query, conn)

    id    name  salary  dep_id  manager_id   hire_date             email
0    1    John   60000       1         NaN  2026-01-15    john@gmail.com
1    2   Alice   80000       1         1.0  2026-02-01   alice@gmail.com
2    6    Emma   90000       1         1.0  2025-06-10    emma@gmail.com
3   10    Isla   95000       1         1.0  2025-04-01    isla@gmail.com
4   12   Karen   83000       1         1.0  2025-07-15   karen@gmail.com
5   15  Nathan   66000       1         1.0  2025-12-01  nathan@gmail.com
6   18   Quinn   43000       1         1.0  2026-02-10   quinn@gmail.com
7    3     Bob   75000       2         1.0  2026-01-20    john@gmail.com
8    4   David   50000       2         3.0  2026-03-01     bob@gmail.com
9    7   Frank   55000       2         3.0  2025-08-20   frank@gmail.com
10  11    Jack   61000       2         3.0  2026-02-20    jack@gmail.com
11  13     Leo   57000       2         3.0  2025-09-01     leo@gmail.com
12  16  Olivia   52000       2         3.0  2026-03-05   frank@gmail.com
13  19  Rachel   79000       2         3.0  2025-10-15  rachel@gmail.com

**Explanation**

- `JOIN department d ON e.dep_id = d.id` connects employees to their department name.
- `WHERE d.name NOT IN ('HR', 'Admin')` excludes any employee whose department is HR or Admin.
- `NOT IN` is the cleanest way to exclude multiple values at once.

Q5. Top 3 Most Ordered Items

## 5. Top 3 Most Ordered Items

**Difficulty:** 🟢 Easy

**Subtopic:** ORDER BY + LIMIT

---

**Table: zomato_orders**
```
+---------------------+---------+
| Column Name         | Type    |
+---------------------+---------+
| user_id             | int     |
| order_id            | int     |
| amount              | int     |
| order_date          | date    |
| delivery_partner_id | int     |
| delivery_rating     | int     |
+---------------------+---------+
```

- `user_id` represents the user who placed the order.
- `amount` represents the total amount of the order.
- `order_date` represents when the order was placed.

---

**Problem**

Write a SQL query to retrieve the **top 3 users** who spent the most on Zomato.

Return `user_id` and `total_amount` ordered from highest to lowest.

**Example 1**

**Input**

zomato_orders table:
```
+---------+----------+--------+------------+---------------------+-----------------+
| user_id | order_id | amount | order_date | delivery_partner_id | delivery_rating |
+---------+----------+--------+------------+---------------------+-----------------+
| 1       | 101      | 200    | 2024-01-01 | 1                   | 5               |
| 1       | 102      | 300    | 2024-01-03 | 2                   | 4               |
| 2       | 103      | 150    | 2024-01-04 | 1                   | 5               |
| 3       | 104      | 400    | 2024-01-05 | 3                   | 3               |
+---------+----------+--------+------------+---------------------+-----------------+
```

**Output**
```
+---------+--------------+
| user_id | total_amount |
+---------+--------------+
| 1       | 500          |
| 3       | 400          |
| 2       | 150          |
+---------+--------------+
```

 CODE (View Table):

In [ ]:
# 👀 Preview the table
print("zomato_orders table:")
pd.read_sql_query("SELECT * FROM zomato_orders", conn)

zomato_orders table:

   user_id  order_id  amount  order_date  delivery_partner_id  delivery_rating
0        1       101     200  2024-01-01                    1                5
1        1       102     300  2024-01-03                    2                4
2        2       103     150  2024-01-04                    1                5
3        3       104     400  2024-01-05                    3                3

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT user_id,
       SUM(amount) AS total_amount
FROM zomato_orders
GROUP BY user_id
ORDER BY total_amount DESC
LIMIT 3
"""

pd.read_sql_query(query, conn)

   user_id  total_amount
0        1           500
1        3           400
2        2           150

**Explanation**

- `GROUP BY user_id` groups all orders by each user.
- `SUM(amount)` calculates the total amount spent by each user.
- `ORDER BY total_amount DESC` sorts from highest spender to lowest.
- `LIMIT 3` returns only the top 3 results.

## 6. Print All Duplicate Emails

**Difficulty:** 🟡 Medium

**Subtopic:** GROUP BY + HAVING

---

**Table: employees**
```
+------------+---------+
| Column Name| Type    |
+------------+---------+
| id         | int     |
| name       | varchar |
| salary     | int     |
| dep_id     | int     |
| manager_id | int     |
| hire_date  | date    |
+------------+---------+
```

> 💡 Note: We use `name` as a proxy for email to demonstrate the duplicate logic. In a real scenario replace `name` with `email`.

---

**Problem**

Write a SQL query to find all **duplicate** values in a table — values that appear **more than once**.

**Example 1**

**Input**

employees table:
```
+----+-------+
| id | name  |
+----+-------+
| 1  | John  |
| 2  | Alice |
| 3  | John  |
| 4  | Bob   |
| 5  | Alice |
+----+-------+
```

**Output**
```
+-------+
| name  |
+-------+
| John  |
| Alice |
+-------+
```

CODE (View Table):

In [ ]:
# 👀 Preview the table
print("employees table:")
pd.read_sql_query("SELECT * FROM employees", conn)

employees table:

    id    name  salary  dep_id  manager_id   hire_date             email
0    1    John   60000       1         NaN  2026-01-15    john@gmail.com
1    2   Alice   80000       1         1.0  2026-02-01   alice@gmail.com
2    3     Bob   75000       2         1.0  2026-01-20    john@gmail.com
3    4   David   50000       2         3.0  2026-03-01     bob@gmail.com
4    5    John   45000       3         3.0  2026-02-15   david@gmail.com
5    6    Emma   90000       1         1.0  2025-06-10    emma@gmail.com
6    7   Frank   55000       2         3.0  2025-08-20   frank@gmail.com
7    8   Grace   72000       3         5.0  2026-01-05   grace@gmail.com
8    9   Henry   48000       3         5.0  2025-11-11   alice@gmail.com
9   10    Isla   95000       1         1.0  2025-04-01    isla@gmail.com
10  11    Jack   61000       2         3.0  2026-02-20    jack@gmail.com
11  12   Karen   83000       1         1.0  2025-07-15   karen@gmail.com
12  13     Leo   57000       2         3.0  2025-09-01     leo@gmail.com
13  14     Mia   74000       3         5.0  2026-01-25     mia@gmail.com
14  15  Nathan   66000       1         1.0  2025-12-01  nathan@gmail.com
15  16  Olivia   52000       2         3.0  2026-03-05   frank@gmail.com
16  17    Paul   88000       3         5.0  2025-05-20    paul@gmail.com
17  18   Quinn   43000       1         1.0  2026-02-10   quinn@gmail.com
18  19  Rachel   79000       2         3.0  2025-10-15  rachel@gmail.com
19  20   Steve   67000       3         5.0  2026-01-30     bob@gmail.com

 CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT name
FROM employees
GROUP BY name
HAVING COUNT(*) > 1
"""

pd.read_sql_query(query, conn)

   name
0  John

**Explanation**

- `GROUP BY name` groups rows by each unique name.
- `COUNT(*)` counts how many times each name appears.
- `HAVING COUNT(*) > 1` keeps only those names that appear **more than once** — i.e., duplicates.
- `HAVING` is used instead of `WHERE` because we are filtering on an aggregated value.

Q7. Companies With ≥2 Users Speaking English AND German

## 7. Companies With At Least 2 Users Speaking English AND German

**Difficulty:** 🟡 Medium

**Subtopic:** GROUP BY + HAVING + DISTINCT

---

**Table: users**
```
+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| user_id     | int     |
| company     | varchar |
| language    | varchar |
+-------------+---------+
```

- `user_id` represents the unique user.
- `company` represents the company the user belongs to.
- `language` represents the language spoken by the user.

---

**Problem**

Write a SQL query to return the names of companies that have **at least one English speaker AND at least one German speaker**.

**Example 1**

**Input**

users table:
```
+---------+---------+----------+
| user_id | company | language |
+---------+---------+----------+
| 1       | Google  | English  |
| 2       | Google  | German   |
| 3       | Google  | French   |
| 4       | Meta    | English  |
| 5       | Meta    | Spanish  |
| 6       | Apple   | English  |
| 7       | Apple   | German   |
+---------+---------+----------+
```

**Output**
```
+---------+
| company |
+---------+
| Google  |
| Apple   |
+---------+
```

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT company
FROM users
WHERE language IN ('English', 'German')
GROUP BY company
HAVING COUNT(DISTINCT language) = 2
"""

pd.read_sql_query(query, conn)

  company
0  Amazon
1   Apple
2  Google

**Explanation**

- `WHERE language IN ('English', 'German')` filters only English and German speakers first.
- `GROUP BY company` groups the filtered rows by company.
- `COUNT(DISTINCT language)` counts how many **distinct** languages (English, German) each company has.
- `HAVING COUNT(DISTINCT language) = 2` ensures the company has **both** English and German speakers — not just one of them.