# Category 3 — HAVING Clause
### Total Questions: 4

---
1.Departments with total salary above a threshold

2.Departments with more than 5 employees

3.Users who placed more than 10 orders

4.Rank users based on total amount spent (with HAVING filter)

# Upload sql_practice.db from your computer

In [ ]:
# ⬆️ Upload sql_practice.db from your computer
from google.colab import files
uploaded = files.upload()
print("✅ Database uploaded!")

Saving sql_practice.db to sql_practice.db
✅ Database uploaded!

# Verify tables loaded

In [ ]:
import sqlite3
import pandas as pd
import os

_cwd = os.getcwd()
_db = os.path.join(_cwd, "sql_practice.db")
if not os.path.isfile(_db):
    _db = os.path.join(os.path.dirname(_cwd), "sql_practice.db")
conn = sqlite3.connect(_db)

# Verify tables loaded
pd.read_sql_query("""
SELECT name FROM sqlite_master
WHERE type='table'
ORDER BY name
""", conn)

               name
0         customers
1        department
2               emp
3   employee_salary
4         employees
5    monthly_salary
6               num
7            orders
8             posts
9          products
10             seat
11          table_a
12          table_b
13          table_x
14          table_y
15      temperature
16            users
17    zomato_orders

# Category 2 — HAVING Clause



## 1. Departments With Total Salary Above a Threshold

**Difficulty:** 🟢 Easy

**Subtopic:** GROUP BY + HAVING

---

**Table: employee_salary**
```
+------------------+---------+
| Column Name      | Type    |
+------------------+---------+
| did              | int     |
| name_of_employee | varchar |
| salary           | int     |
+------------------+---------+
```

- `did` represents the department ID.
- `name_of_employee` represents the employee's name.
- `salary` represents the employee's salary.

Each department may contain multiple employees.

---

**Problem**

Write a SQL query to return the departments whose **total salary is greater than 180000**.

Return the `did` and `total_salary` for those departments only.

**Example 1**

**Input**

employee_salary table:
```
+-----+------------------+--------+
| did | name_of_employee | salary |
+-----+------------------+--------+
| 1   | Alice            | 50000  |
| 1   | Bob              | 65000  |
| 1   | Carol            | 60000  |
| 2   | David            | 70000  |
| 2   | Emma             | 72000  |
| 2   | Frank            | 68000  |
| 3   | Anna             | 55000  |
| 3   | George           | 52000  |
| 3   | Henry            | 51000  |
+-----+------------------+--------+
```

**Output**
```
+-----+--------------+
| did | total_salary |
+-----+--------------+
| 1   | 175000       |
| 2   | 210000       |
+-----+--------------+
```

CODE (View Table):

In [ ]:
# 👀 Preview the table
print("employee_salary table:")
pd.read_sql_query("SELECT * FROM employee_salary", conn)

employee_salary table:

   did name_of_employee  salary
0    1            Alice   50000
1    1              Bob   65000
2    1            Carol   60000
3    2            David   70000
4    2             Emma   72000
5    2            Frank   68000
6    3             Anna   55000
7    3           George   52000
8    3            Henry   51000

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT did,
       SUM(salary) AS total_salary
FROM employee_salary
GROUP BY did
HAVING SUM(salary) > 180000
"""

pd.read_sql_query(query, conn)

   did  total_salary
0    2        210000

**Explanation**

- `GROUP BY did` groups all employees by their department.
- `SUM(salary)` calculates the total salary for each department.
- `HAVING SUM(salary) > 180000` filters out departments whose total salary is **not** above 180000.
- Key difference — `WHERE` filters **individual rows** before grouping, `HAVING` filters **groups** after aggregation.

## 2. Departments With More Than 5 Employees

**Difficulty:** 🟢 Easy

**Subtopic:** GROUP BY + HAVING + COUNT

---

**Table: employee_salary**
```
+------------------+---------+
| Column Name      | Type    |
+------------------+---------+
| did              | int     |
| name_of_employee | varchar |
| salary           | int     |
+------------------+---------+
```

- `did` represents the department ID.
- `name_of_employee` represents the employee's name.
- `salary` represents the employee's salary.

---

**Problem**

Write a SQL query to return the departments that have **more than 2 employees**.

> 💡 Note: Our table has max 3 employees per department so we use `> 2` to demonstrate the concept. In real scenarios this threshold would be higher.

Return the `did` and `employee_count`.

**Example 1**

**Input**

employee_salary table:
```
+-----+------------------+--------+
| did | name_of_employee | salary |
+-----+------------------+--------+
| 1   | Alice            | 50000  |
| 1   | Bob              | 65000  |
| 1   | Carol            | 60000  |
| 2   | David            | 70000  |
| 2   | Emma             | 72000  |
| 2   | Frank            | 68000  |
| 3   | Anna             | 55000  |
| 3   | George           | 52000  |
| 3   | Henry            | 51000  |
+-----+------------------+--------+
```

**Output**
```
+-----+----------------+
| did | employee_count |
+-----+----------------+
| 1   | 3              |
| 2   | 3              |
| 3   | 3              |
+-----+----------------+
```

CODE (View Table):

In [ ]:
# 👀 Preview the table
print("employee_salary table:")
pd.read_sql_query("SELECT * FROM employee_salary", conn)

employee_salary table:

   did name_of_employee  salary
0    1            Alice   50000
1    1              Bob   65000
2    1            Carol   60000
3    2            David   70000
4    2             Emma   72000
5    2            Frank   68000
6    3             Anna   55000
7    3           George   52000
8    3            Henry   51000

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT did,
       COUNT(*) AS employee_count
FROM employee_salary
GROUP BY did
HAVING COUNT(*) > 2
"""

pd.read_sql_query(query, conn)

   did  employee_count
0    1               3
1    2               3
2    3               3

**Explanation**

- `GROUP BY did` groups rows by department.
- `COUNT(*)` counts the number of employees in each department.
- `HAVING COUNT(*) > 2` keeps only departments with **more than 2 employees**.
- Remember — you cannot use `WHERE COUNT(*) > 2` because `WHERE` does not work on aggregated values. Always use `HAVING` for that.

## 3. Users Who Placed More Than 1 Order

**Difficulty:** 🟢 Easy

**Subtopic:** GROUP BY + HAVING + COUNT

---

**Table: zomato_orders**
```
+---------------------+---------+
| Column Name         | Type    |
+---------------------+---------+
| user_id             | int     |
| order_id            | int     |
| amount              | int     |
| order_date          | date    |
| delivery_partner_id | int     |
| delivery_rating     | int     |
+---------------------+---------+
```

- `user_id` represents the user who placed the order.
- `order_id` represents the unique order.
- `amount` represents the order amount.

---

**Problem**

Write a SQL query to find all users who have placed **more than 1 order**.

Return `user_id` and `order_count`.

**Example 1**

**Input**

zomato_orders table:
```
+---------+----------+--------+------------+---------------------+-----------------+
| user_id | order_id | amount | order_date | delivery_partner_id | delivery_rating |
+---------+----------+--------+------------+---------------------+-----------------+
| 1       | 101      | 200    | 2024-01-01 | 1                   | 5               |
| 1       | 102      | 300    | 2024-01-03 | 2                   | 4               |
| 2       | 103      | 150    | 2024-01-04 | 1                   | 5               |
| 3       | 104      | 400    | 2024-01-05 | 3                   | 3               |
+---------+----------+--------+------------+---------------------+-----------------+
```

**Output**
```
+---------+-------------+
| user_id | order_count |
+---------+-------------+
| 1       | 2           |
+---------+-------------+
```

 CODE (View Table):

In [ ]:
# 👀 Preview the table
print("zomato_orders table:")
pd.read_sql_query("SELECT * FROM zomato_orders", conn)

zomato_orders table:

   user_id  order_id  amount  order_date  delivery_partner_id  delivery_rating
0        1       101     200  2024-01-01                    1                5
1        1       102     300  2024-01-03                    2                4
2        2       103     150  2024-01-04                    1                5
3        3       104     400  2024-01-05                    3                3

CODE (Solution):

In [ ]:
# ✅ Solution
query = """
SELECT user_id,
       COUNT(order_id) AS order_count
FROM zomato_orders
GROUP BY user_id
HAVING COUNT(order_id) > 1
"""

pd.read_sql_query(query, conn)

   user_id  order_count
0        1            2

**Explanation**

- `GROUP BY user_id` groups all orders by each user.
- `COUNT(order_id)` counts how many orders each user placed.
- `HAVING COUNT(order_id) > 1` keeps only users who placed **more than 1 order**.
- User 1 placed 2 orders so they appear. Users 2 and 3 placed only 1 order each so they are excluded.

## 4. Department With Minimum Average Salary

**Difficulty:** 🟡 Medium

**Subtopic:** GROUP BY + HAVING + MIN + Subquery

---

**Table: employee_salary**
```
+------------------+---------+
| Column Name      | Type    |
+------------------+---------+
| did              | int     |
| name_of_employee | varchar |
| salary           | int     |
+------------------+---------+
```

- `did` represents the department ID.
- `name_of_employee` represents the employee's name.
- `salary` represents the employee's salary.

---

**Problem**

Write a SQL query to return the department with the **minimum average salary**.

Return the `did` and `avg_salary`.

**Example 1**

**Input**

employee_salary table:
```
+-----+------------------+--------+
| did | name_of_employee | salary |
+-----+------------------+--------+
| 1   | Alice            | 50000  |
| 1   | Bob              | 65000  |
| 1   | Carol            | 60000  |
| 2   | David            | 70000  |
| 2   | Emma             | 72000  |
| 2   | Frank            | 68000  |
| 3   | Anna             | 55000  |
| 3   | George           | 52000  |
| 3   | Henry            | 51000  |
+-----+------------------+--------+
```

**Output**
```
+-----+------------+
| did | avg_salary |
+-----+------------+
| 3   | 52666.67   |
+-----+------------+
```

In [ ]:
# 👀 Preview the table
print("employee_salary table:")
pd.read_sql_query("SELECT * FROM employee_salary", conn)

employee_salary table:

   did name_of_employee  salary
0    1            Alice   50000
1    1              Bob   65000
2    1            Carol   60000
3    2            David   70000
4    2             Emma   72000
5    2            Frank   68000
6    3             Anna   55000
7    3           George   52000
8    3            Henry   51000

In [ ]:
# ✅ Solution
query = """
SELECT did,
       AVG(salary) AS avg_salary
FROM employee_salary
GROUP BY did
HAVING AVG(salary) = (
    SELECT MIN(avg_sal)
    FROM (
        SELECT AVG(salary) AS avg_sal
        FROM employee_salary
        GROUP BY did
    )
)
"""

pd.read_sql_query(query, conn)

   did    avg_salary
0    3  52666.666667

**Explanation**

- The **inner subquery** calculates `AVG(salary)` for each department.
- The **middle subquery** wraps it to find the `MIN()` of those averages.
- The **outer query** uses `HAVING` to keep only the department whose average salary equals that minimum value.
- This is a classic pattern — use a subquery inside `HAVING` when you need to compare an aggregate against another aggregate.